local version = require("cinezoom.version")

return function(t)
    t.test("parses plain versions", function()
        local v = version.parse("30.2.3")
        t.eq(v.major, 30); t.eq(v.minor, 2); t.eq(v.patch, 3)
    end)
    t.test("parses release candidates", function()
        local v = version.parse("31.0.0-rc1")
        t.eq(v.major, 31); t.eq(v.minor, 0); t.eq(v.patch, 0)
    end)
    t.test("parses 32.0.1 and 29.1.2", function()
        t.eq(version.parse("32.0.1").major, 32)
        local v = version.parse("29.1.2")
        t.eq(v.minor, 1); t.eq(v.patch, 2)
    end)
    t.test("30.10 is not 30.1", function()
        t.eq(version.parse("30.10").minor, 10)
        t.truthy(version.at_least("30.10.0", 30, 2, 0))
    end)
    t.test("garbage parses to zeros", function()
        t.eq(version.parse("nope").major, 0)
        t.eq(version.parse(nil).major, 0)
    end)
    t.test("at_least", function()
        t.truthy(version.at_least("30.0.0", 30))
        t.truthy(version.at_least("29.1.3", 29, 1, 3))
        t.truthy(not version.at_least("29.1.2", 29, 1, 3))
        t.truthy(version.at_least("31.0.0-rc1", 30, 99, 99))
        t.truthy(not version.at_least("29.9.9", 30))
    end)
end
